export const ADD_BALANCE = "UPDATE_BALANCE";
export const ADD_ADDRESS = "ADD_ADDRESS";

export const ADD_INSTANCE = "ADD_INSTANCE";
export const ADD_STATE_MANAGER = "ADD_STATE_MANAGER";

export const ADD_REGISTRATION_STATUS = "ADD_REGISTRATION_STATUS";

